# Generated by Django 2.2 on 2021-09-30 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_auto_20210930_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='createdon',
            new_name='created_on',
        ),
        migrations.AlterField(
            model_name='profilefeeditem',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
